name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/github.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Sync
        uses: micnncim/action-label-syncer@v1.2.0
        with:
          manifest: .github/labels.yml
          repository: ${{ matrix.repo }}
          token: ${{ secrets.LABEL_SYNC_PAT }}
          prune: false
